NoPermission: "&cInsufficient permission."
Missing-arg: "&bPlease add message to your command."
Reload: "&bConfiguration reloaded successfully."
Prefix: "&8&l[&b&lAdvanced&f&lBroadcast&8&l] &8>> &r"
Help: "&b&m-----&r&f&m-----&r&8[&b&lAdvanced&f&lBroadcast&8]&f&m-----&r&b&m-----&r"
CommandHelp: "&b/advancedBroadcast help &8- &fShow this page"
CommandReload: "&b/advancedBroadcast reload &8- &fReload the plugin"
CommandAlert: "&b/aba &8- &fSend Alert Broadcast"
CommandReboot: "&b/abr &8- &fSend Reboot Broadcast"
CommandServer: "&b/abs &8- &fSend Server Broadcast"
CommandInformation: "&b/abi &8- &fSend Information Broadcast"
HelpEnd: "&b&m-----&r&f&m-----&r&8[&b&lAdvanced&f&lBroadcast&8]&f&m-----&r&b&m-----&r"
Usage: "&bUsage &8: &f&l/advancedBroadcast help"
Alert-Broadcast: "&8&l[&c&lALERT&8&l] &r"
Reboot-Broadcast: "&8&l[&c&lREBOOT&8&l] &r"
Server-Broadcast: "&8&l[&c&lMY SERVER NAME&8&l] &r"
Information-Broadcast: "&8&l[&c&lINFORMATION&8&l] &r"
